name: Deploy Images to GHCR

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  push-container-image:
    permissions:
      packages: write
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
     - uses: actions/checkout@main
     - name: Install Nix
       uses: cachix/install-nix-action@v22
       with:
         github_access_token: ${{ secrets.GITHUB_TOKEN }}
     - name: Build container image
       run: nix build .#streamedContainer
     - name: Setup docker (missing on MacOS)
       if: runner.os == 'macos'
       run: |
         brew install docker
         colima start
         
         # For testcontainers to find the Colima socket
         # https://github.com/abiosoft/colima/blob/main/docs/FAQ.md#cannot-connect-to-the-docker-daemon-at-unixvarrundockersock-is-the-docker-daemon-running
         sudo ln -sf $HOME/.colima/default/docker.sock /var/run/docker.sock
     - name: 'Login to GitHub Container Registry'
       uses: docker/login-action@v3
       with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
     - name: 'Push Container Image'
       run: |
         ./result | docker load
         docker tag stable-diffusion-bot:latest ghcr.io/capslock/stable-diffusion-bot:latest
         docker push ghcr.io/capslock/stable-diffusion-bot:latest
